### ISSUE TITLE
Ashish's Tasks

### ISSUE THREAD

**Issue by Xplod4432** [Xplod4432/shopbricks#1]
@AndyyAD  tasks toward CSE326 Group Project:

- [x] Description of modules and work taken up by each member (Pre-Submission Report}
- [x] Hompage
- [x] Login Page

Layout as given by faculty
![1](https://user-images.githubusercontent.com/73468854/112761426-e6c1af80-9018-11eb-9ab9-05ec77df46cf.png)

**Comment by AndyyAD** [comment]
Pre-Submission file not required
